Support switch languages in the context menu #83
pairmesh/pairmesh pull request #88
Opened 2022-04-01 14:09 UTC by lingkeyang

2022-04-02 01:37 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +    title_not_login: "Need Login into PairMesh"
Please log in to PairMesh

2022-04-02 01:38 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +    title_foramt: "Certification will expires in %d hours"
Certificate expires in %d hours

2022-04-02 01:38 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +    tips: "Online Current Node"
Current Online Nodes

2022-04-02 01:39 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +    tips: "Offline Current Node"
Current Offline Nodes

2022-04-02 01:39 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +    tips: "Login into PairMesh Console"
Login to PairMesh Console

2022-04-02 01:59 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +  my_devices: "My Device"
My Devices

2022-04-02 02:00 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +  my_networks: "My Network"
My Networkds

2022-04-02 02:02 UTC, vodkaslime requested changes
Nice work! Commented on the en_us translation part.

2022-04-03 05:51 UTC, vodkaslime commented on i18n/locales/en_US.yaml
> +  my_networks: "My Networkds"
Networks

2022-04-03 11:17 UTC, vodkaslime approved these changes
Well done, LGTM

2022-04-04 03:04 UTC, hi-windy approved these changes

2022-04-04 03:07 UTC, merged

2022-04-04 03:07 UTC, hi-windy commented
Nice work!

@lingkeyang Thanks for your contribution.